version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-image-transfer-test:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    working_dir: /usr/src/app
    command: "npm start"
